name: SoSeller
version: '${project.version}'
main: org.sausagedev.soseller.SoSeller
api-version: '1.19'
load: STARTUP
softdepend:
  - PlayerPoints
  - PlaceholderAPI
  - CoinsEngine
depend:
  - Vault
loadbefore:
  - Vault
commands:
  soseller:
    aliases:
      - seller
      - sell
      - buyer
      - offer